version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/website"
    schedule:
      interval: "daily"

  - package-ecosystem: "github-actions"
    directory: "/website"
    schedule:
      interval: "daily"

  - package-ecosystem: "cargo"
    directory: "/program"
    schedule:
      interval: "daily"
